version: '3.4'

services:
  visualjavaweb:
    image: visualjavaweb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:8080
